### ISSUE TITLE
Codecov not recognizing tests

### ISSUE THREAD

**Issue by bschilder** [bschilder/ThreeWayTest#19]
Codecov coverage is not updating:
![Screenshot 2023-03-03 at 12 28 34](https://user-images.githubusercontent.com/34280215/222720294-5f603f49-c2f6-499e-96e7-c8fcc3a1f7dc.png)

For whatever reason, the coverage tests are not being run by Codecov. It's possible this is simply a bug on their end as I noticed there were recently other issues regarding the rendering of coverage badges (which were showing up as "not found" despite having coverage data on the associate Codecov page):
https://app.codecov.io/gh/bschilder/ThreeWayTest/tree/master/R

It's also possible that something has gone awry with the test/upload code coverage steps in `rworkflows`:
https://github.com/neurogenomics/rworkflows/blob/24ca1e99062b52d03b78bcf2eec869cd7d2e189f/action.yml#L313

If this doesn't resolve itself soon, I'll continue looking into it further.

**Comment by bschilder** [comment]
Figured it out! Somehow the *tests/testthat.R* went missing and thus unit tests were not actually being run.

![Screenshot 2023-03-08 at 11 46 44](https://user-images.githubusercontent.com/34280215/223705804-6ccb0bbc-b5ea-4296-8a82-ab405100cc36.png)

Just pushed to retrigger code coverage tests, but based on my local run `ThreeWayTest` has a whopping 100%! This is usually rather hard to achieve and ensure that your package will work robustly across a wide variety of scenarios. @ftdbdl 

`devtools::test_coverage()`

![Screenshot 2023-03-08 at 12 10 48](https://user-images.githubusercontent.com/34280215/223710172-749b35f5-39aa-43a3-a1ae-162c5198f082.png)

**Comment by ftdbdl** [comment]
Sorry I miss the first comment! I will further check our package and make sure it works robustly across a wide variety of scenarios.

**Comment by bschilder** [comment]
> Sorry I miss the first comment! I will further check our package and make sure it works robustly across a wide variety of scenarios.

No worries, this one was stumping me until I noticed the missing file just now. But things are looking really good now!
